import type { Post, Comment } from './types';

export const postsMock = [
  {
    id: 'morning-walk',
    author: 'Maya Brooks',
    handle: '@mayab',
    avatarColor: '#ef8354',
    publishedAt: '18 min',
    text: 'Slow mornings, good coffee, and nowhere urgent to be. A solid start to the weekend.',
    imageUrl:
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=85',
    imageAlt: 'A warm cup of coffee on a wooden table',
    likes: 128,
    replies: 12,
    comments: 9,
  },
  {
    id: 'small-progress',
    author: 'Noah Kim',
    handle: '@noahmakes',
    avatarColor: '#5f6fff',
    publishedAt: '1 hr',
    text: 'Reminder: small progress is still progress. I shipped the first version of a project I have been overthinking for weeks — and it feels great.',
    likes: 84,
    replies: 7,
    comments: 14,
  },
  {
    id: 'quiet-places',
    author: 'Iris Chen',
    handle: '@irisoutside',
    avatarColor: '#38a169',
    publishedAt: '3 hrs',
    text: 'Found a quiet place at the edge of the city. Keeping this one on my list for slow Sunday walks.',
    imageUrl:
      'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=85',
    imageAlt: 'A quiet mountain lake surrounded by green hills',
    likes: 246,
    replies: 28,
    comments: 21,
  },
  {
    id: 'first-sketch',
    author: 'Eli Turner',
    handle: '@eliturner',
    avatarColor: '#e76f51',
    publishedAt: '5 hrs',
    text: 'Sharing the first sketch before I talk myself out of it. Still rough, but I like where it is going.',
    likes: 16,
    replies: 2,
    comments: 0,
  },
] satisfies readonly Post[]

export const commentsByPostId: Readonly<Record<string, readonly Comment[]>> = {
  'morning-walk': [
    {
      id: 'coffee-shop',
      author: 'Lena Ortiz',
      handle: '@lenao',
      avatarColor: '#9b5de5',
      publishedAt: '12 min',
      text: 'Comment1',
      likes: 18,
    },
    {
      id: 'same-energy',
      author: 'Theo Martin',
      handle: '@theom',
      avatarColor: '#00a896',
      publishedAt: '8 min',
      text: 'Comment2',
      likes: 7,
    },
    {
      id: 'book-too',
      author: 'Ava Singh',
      handle: '@avareads',
      avatarColor: '#f4a261',
      publishedAt: '3 min',
      text: 'Comment3',
      likes: 11,
    },
  ],
  'small-progress': [
    {
      id: 'shipping-wins',
      author: 'Jordan Lee',
      handle: '@jordanbuilds',
      avatarColor: '#277da1',
      publishedAt: '52 min',
      text: 'Comment4!',
      likes: 24,
    },
    {
      id: 'needed-this',
      author: 'Sam Rivera',
      handle: '@samrivera',
      avatarColor: '#f94144',
      publishedAt: '31 min',
      text: 'Comment5',
      likes: 15,
    },
  ],
  'quiet-places': [
    {
      id: 'beautiful-view',
      author: 'Emma Wilson',
      handle: '@emmawanders',
      avatarColor: '#577590',
      publishedAt: '2 hrs',
      text: 'Comment6',
      likes: 32,
    },
    {
      id: 'save-this',
      author: 'Lucas Park',
      handle: '@lucaspark',
      avatarColor: '#43aa8b',
      publishedAt: '1 hr',
      text: 'Comment7',
      likes: 9,
    },
    {
      id: 'peaceful',
      author: 'Nora Ellis',
      handle: '@norae',
      avatarColor: '#f8961e',
      publishedAt: '44 min',
      text: 'Comment8',
      likes: 13,
    },
  ],
}
